### ISSUE TITLE
Library memory allocation error  - testcbsdk not working on mac

### ISSUE THREAD

**Issue by silversd13** [CerebusOSS/CereLink#106]
I installed Release CereLink-7.0.4 on my Mac Air running os10.13.6.

I followed the instructions to install CereLink, which worked.
I followed the instructions to change the buffer sizes, which worked.

When running CereLink-7.0.4/dist/bin/testcbsdk I get the following error:
    Unable to open instrument connection.
    Library memory allocation error
    testOpen failed (-26)!

![Screen Shot 2019-05-25 at 4 07 16 PM](https://user-images.githubusercontent.com/5520438/58375416-52abcc00-7f07-11e9-845d-ce23e9044372.png)

**Comment by cboulay** [comment]
It's been a very long time since I tested on Mac, and unfortunately I probably won't be able to test again on Mac until mid-July.

**Comment by silversd13** [comment]
Ok, it would be great if you have any suggestions for how to move forward or any debugging steps that I can take to at least diagnose the problem.

Thanks for your help,

**Comment by silversd13** [comment]
Hi,

I was wondering if you have had any time to look into this issue. Big picture - I'd like to read blackrock data into Matlab on a Mac.

**Comment by dashesy** [comment]
`cbmex` may be not up to date, can you try the latest `cbpy`?

**Comment by silversd13** [comment]
We have a large codebase in Matlab and we were hoping that we could continue to use it going forward. Is there anyway to check if cbmex has been updated?

**Comment by dashesy** [comment]
Those version issues could be because you may need to compile cbmex from source. 'cboct' is already compiled if you have octave-devel, but you need Matlab to compile cbmex.

**Comment by silversd13** [comment]
I thought that cbmex was compiled during the build process. 

I've tried both suggested build methods to no avail. Should I be compiling cbmex separately?
```
brew install cmake qt
cmake -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 .
sudo make all
sudo make install
```
and
```
brew install cmake qt
mkdir build
cd build
cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
cmake --build . --config Release
```

**Comment by dashesy** [comment]
Did you set the MATLAB directory like [this](https://github.com/dashesy/CereLink/blob/master/CMakeLists.txt#L11)?

**Comment by silversd13** [comment]
I began trying to load data into python to at least see if this is a Matlab specific issue. I am able to install cbpy, but when I try the following code I continue to get an error message.

```
# Imports
   ...: import time
   ...: import traceback
   ...: 
   ...: from cerebus import cbpy
   ...: 
   ...: # Connection parameters
   ...: connection_params = {
   ...:     'central-addr'        : '255.255.255.255',
   ...:     'central-port'        : 51002,
   ...:     'inst-addr'           : '192.168.137.128',
   ...:     'inst-port'           : 51001,
   ...:     'receive-buffer-size' : 8388608
   ...: }
   ...: 
   ...: # Trial configuration parameters. For best performance, it seems the
   ...: # lengths should be greater than the maximum amount of samples that is
   ...: # expected across all of the channels given the refresh rate.
   ...: trial_config_params = {
   ...:     'buffer_parameter' : {
   ...:         'double'            : True,
   ...:         'continuous_length' : 35000,
   ...:         'event_length'      : 35000,
   ...:         'absolute'          : True,
   ...:     }
   ...: }

connection_num, connection_info = cbpy.open(parameter=connection_params)
```

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> RuntimeError: -26, No associated error string. See cbsdk.h
> Exception ignored in: 'cerebus.cbpy.handle_result'
> RuntimeError: -26, No associated error string. See cbsdk.h
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> RuntimeError: -4, Interface is closed; cannot do this operation.
> Exception ignored in: 'cerebus.cbpy.handle_result'
> RuntimeError: -4, Interface is closed; cannot do this operation.

**Comment by cboulay** [comment]
I finally got around to testing this. I'm running the testcbsdk script in Xcode in debug mode. I keep running into QSharedMemory create errors InvalidSize. If I manually override the size, I have to go down to 8192 before it will allow me to continue, and that's obviously too small.

I'm not sure what changed in MacOS or Qt where setting kern.sysv.shmmax no longer works, or maybe some other problem.

So, it may be time to switch to `mmap`. Unfortunately, I don't foresee when I'd have time to do this.
