### ISSUE TITLE
Blackrock Microsystems New File Format (3.0)

### ISSUE THREAD

**Issue by NickHalper** [CerebusOSS/CereLink#114]
Blackrock is expecting a change to our file format in an upcoming release (I think at least a couple of months away), so I wanted to reach out to you to make sure it is on your radar for incorporation into Cerelink. As always, we will allow people access to our previous file formats, and the adoption will be slow, so this would be supported in addition to the current ones that you load. 

The primary change is a move to 64 bit timestamps. The other change is the inclusion of an additional event type in our Neural Events File: an indicator for the recording pausing, resuming, and stopping. 

We can provide the file spec as soon as it is all signed off on our side, which should be in just a couple of weeks. 

Is this something that would be possible for you to incorporate? Besides example of files that uses this new format, is there anything else you would need from us?

Note that this would affect timestamps reported in cbmex/cbsdk as well, so O suppose it is more accurate to say "new packet structure".

Nick

**Comment by cboulay** [comment]
Hi Nick!
Cool, those are all welcome additions.

We'll need the new headers. Without diving in I don't yet know what else we'll need. If there are any changes to the way packet types or channel types are enumerated then we may need some more support to get over that initial "how do they expect us to do it?" hump.
-Chad

**Comment by dkluger** [comment]
Chad,
Beyond Blackrock's new file format and new packet type, there is also a major change in that Central will be able to handle data from two NSPs in a single instance. This new software will also support up to 512 channels in a single instance.

Keep your eyes open for a release to version 8.0.0. We are about to release 7.0.6, but this version will not have the aforementioned changes.

Once this is released, we can discuss materials you'll need from us to update your Cerelink distribution. We can also then provide more direct interaction to get over specific issues you may be having.

Best,
David

**Comment by cboulay** [comment]
This issue should have been closed two releases ago.
