### ISSUE TITLE
cbhwlib/XmlFile.cpp fails to compile since changes for Qt6 compatiblity in commit 44d8ebfd6e6567c1aafde279ca5c673d847efc01

### ISSUE THREAD

**Issue by janbraun** [CerebusOSS/CereLink#126]
I don't know if it is considered possible to have the code compile with qt5 and qt6 at the same time, bit I would very much appreciate a transitional period which would allow to use both, qt5 and qt6, at the same time.

**Comment by cboulay** [comment]
As mentioned in the linked PR, any efforts to fix Qt compatibility should go towards ripping out the Qt dependency altogether, so I'm closing this issue.

All that remains of Qt is XML, a QApplication (which can be replaced with a `main` and some threads), and a couple signals and slots. I'm not sure how to replace the latter, [but here's a discussion on signaling libraries in C](https://julienjorge.medium.com/testing-c-signal-slot-libraries-1994eb120826). It looks like asio/signals2 is a popular combination, which could also be applied to the QAapplication replacement.

I looked into replacing QXML with pugixml and it's not so bad. I just need to decide if I want to do a functional-only replacement or if I want to create something like a `libCCF`.
