### ISSUE TITLE
Is PyQt needed when I use "cerebus.cbpy" ?

### ISSUE THREAD

**Issue by gefei456** [CerebusOSS/CereLink#127]

**Comment by cboulay** [comment]
Not necessarily. It needs Qt when building, and when running. Installing PyQt is the easiest way to satisfy the latter requirement.
But you could probably do a `DYLD_LIBRARY_PATH=path/to/qt/bin python my_cbpy_scripyt.py` and then you might be able to get away with not installing PyQt. I haven't tried this.

**Comment by gefei456** [comment]
Thanks!!
