### ISSUE TITLE
When I use python in CerePlex for data acquisition, cannot get the expected data

### ISSUE THREAD

**Issue by gefei456** [CerebusOSS/CereLink#128]
"CerebusOSS/CereLink/tree/master/samples/Python"
When I use .py in Python, I cannot get the expected data. However I use matlab, the data received is expected.
When I run [fetch_data_events.py](https://github.com/CerebusOSS/CereLink/blob/master/samples/Python/fetch_data_events.py), the format of data that received is chaos, while I use cbmax, the data is analysable.

Does it require special configuration when I use python to get the cereplex device data?
Why can't I get the correct format by running samples.

thanks!

**Comment by gefei456** [comment]
By the way, python is 3.7

**Comment by gefei456** [comment]
The cause of the error has been found. The python script does not fetch the correct data due to the ”CerePlex Direct“ version used is 7.5.2. The older 7.05 version does.

**Comment by cboulay** [comment]
Thanks for coming back to this.
Yes, CereLink is updated to add features, fix bugs, and to keep compatibility with current NSP firmware. It would be too much work to maintain different versions of CereLink for each NSP firmware version, so if you're stuck on an older firmware version then you're stuck with an older CereLink version too.
