### ISSUE TITLE
Building from source fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by G00Z-G00Z** [CerebusOSS/CereLink#134]
I read the instructions in the build.md file, and followed the instructions exactly. However, I get the following error: 
```
  Building wheel for cerebus (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cerebus (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /tmp/pip-build-env-li4u6t69/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      /CereLink/install False
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing cerebus.egg-info/PKG-INFO
      writing dependency_links to cerebus.egg-info/dependency_links.txt
      writing top-level names to cerebus.egg-info/top_level.txt
      reading manifest file 'cerebus.egg-info/SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'cerebus.egg-info/SOURCES.txt'
      running build_ext
      skipping 'cerebus/cbpy.cpp' Cython extension (up-to-date)
      building 'cerebus.cbpy' extension
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-li4u6t69/overlay/lib/python3.10/site-packages/numpy/core/include -I/media/edy-gomez/personal-files/clases/intercambio-michigan/monkey-lab/CereLink/install/include -I/media/edy-gomez/personal-files/clases/intercambio-michigan/monkey-lab/CereLink/venv/include -I/usr/include/python3.10 -c cerebus/cbpy.cpp -o build/temp.linux-x86_64-cpython-310/cerebus/cbpy.o
      cerebus/cbpy.cpp:764:10: fatal error: cbproto.h: No such file or directory
        764 | #include "cbproto.h"
            |          ^~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cerebus
Failed to build cerebus
ERROR: Could not build wheels for cerebus, which is required to install pyproject.toml-based projects
```

Note that the error is that the `cbproto.h` file is missing. I just cloned the
repo and haven't move anything. 

Could you help me solve the problem?

**Comment by cboulay** [comment]
Did you use CMake to configure, build, and install? Was the install directory set to {repo_root}/install?

Please take a look at the GitHub Actions workflow, which runs on Ubuntu:

https://github.com/CerebusOSS/CereLink/blob/master/.github/workflows/build_cbsdk.yml#L62-L79

**Comment by cboulay** [comment]
Glad you got it building! I definitely want to encourage as many people to be able to build from source as possible, but if you just need some pre-compiled binaries then please remember to check the repo's "releases" page to see if there's anything there for you already.

As for documentation...

The C-API is meant to be very similar to that of cbSDK that comes with Central on Windows. So if you get the Central distribution from the Blackrock website, install it on a windows computer, then you can read the documentation.

The Python interface doesn't have its own documentation other than the comments in the source ([e.g.](https://github.com/CerebusOSS/CereLink/blob/master/cerebus/cbpy.pyx#L72-L92)).

Additionally, you can refer to the [Samples folder](https://github.com/CerebusOSS/CereLink/tree/master/samples) and I use cerebus.cbpy pretty heavily in my [OpenMER project](https://github.com/SachsLab/openmer).
