### ISSUE TITLE
Cannot find library

### ISSUE THREAD

**Issue by somalcy** [CerebusOSS/CereLink#135]
Hi,

We use cmake to compile the cerebus and it gives the following error

```
[  5%] Automatic MOC for target cbsdk_static
[  5%] Automatic MOC for target n2h5
[  8%] Automatic MOC for target cbsdk
[  8%] Built target cbsdk_static_autogen
[  8%] Built target cbsdk_autogen
[  8%] Built target n2h5_autogen
[ 20%] Built target n2h5
[ 60%] Built target cbsdk
[100%] Built target cbsdk_static
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: CBSDK
CPack: - Install project: CBSDK []
CPack: Create package
CPackDeb: - Generating dependency list
CMake Error at /usr/share/cmake-3.16/Modules/Internal/CPack/CPackDeb.cmake:317 (message):
  CPackDeb: dpkg-shlibdeps: 'dpkg-shlibdeps: error: cannot find library
  libQt6Xml.so.6 needed by ./opt/CBSDK/lib64/libcbsdk.so.7.6 (ELF format:
  'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')

  dpkg-shlibdeps: error: cannot find library libQt6Core.so.6 needed by
  ./opt/CBSDK/lib64/libcbsdk.so.7.6 (ELF format: 'elf64-x86-64' abi:
  '0201003e00000000'; RPATH: '')

  dpkg-shlibdeps: error: cannot find library libhdf5.so.103 needed by
  ./opt/CBSDK/bin/n2h5 (ELF format: 'elf64-x86-64' abi: '0201003e00000000';
  RPATH: '')

  dpkg-shlibdeps: error: cannot find library libhdf5_hl.so.100 needed by
  ./opt/CBSDK/bin/n2h5 (ELF format: 'elf64-x86-64' abi: '0201003e00000000';
  RPATH: '')

  dpkg-shlibdeps: error: cannot continue due to the errors listed above

  Note: libraries are not searched in other binary packages that do not have
  any shlibs or symbols file.

  To help dpkg-shlibdeps find private libraries, you might need to use -l.

  ';

  executed command: '/usr/bin/dpkg-shlibdeps --ignore-missing-info -O
  ./opt/CBSDK/bin/n2h5;./opt/CBSDK/lib64/libcbsdk.so.7.6';

  found files: './opt/CBSDK/lib64/libcbsdk_static.a: current ar archive

  ';

  files info: './opt/CBSDK/bin/n2h5: ELF 64-bit LSB shared object, x86-64,
  version 1 (SYSV), dynamically linked, interpreter
  /lib64/ld-linux-x86-64.so.2,
  BuildID[sha1]=bdf44e0910b207c636223d1ba220df00275bae28, for GNU/Linux
  3.2.0, not stripped

  ;./opt/CBSDK/include/cbhwlib.h: C source, ASCII text, with CRLF line
  terminators

  ;./opt/CBSDK/include/cbproto.h: C source, ASCII text

  ;./opt/CBSDK/include/cbsdk.h: C source, ASCII text

  ;./opt/CBSDK/lib64/libcbsdk.so: symbolic link to libcbsdk.so.7.6

  ;./opt/CBSDK/lib64/libcbsdk.so.7.6: ELF 64-bit LSB shared object, x86-64,
  version 1 (GNU/Linux), dynamically linked,
  BuildID[sha1]=d1be36cfcc81e23adc7ada7ad24d6e120f443579, not stripped

  ;./opt/CBSDK/lib64/libcbsdk_static.a: current ar archive

  ';

  binary files: './opt/CBSDK/bin/n2h5;./opt/CBSDK/lib64/libcbsdk.so.7.6'
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/Internal/CPack/CPackDeb.cmake:763 (cpack_deb_prepare_package_vars)
```

We use `cmake -B build -S . -DCMAKE_PREFIX_PATH="/home/dell/Qt6.1.2/6.1.2/gcc_64" -DBUILD_TEST=OFF` to build and `cmake --build build --target package --config Release -j` to compile the code.

The system is ubuntu 20.04 and qt version is 6.1.2.

How to fix this problem?

Soma

**Comment by cboulay** [comment]
Do you actually need to build the `package` target? Are you building this on one computer and bringing it to another? If that's what you are trying to do, will one of the `focal-` packages from this repo's releases page work for you?

If you really need to build the package yourself, then I'm pretty sure we can fix it.

I think the error is that CPack can't find Qt6. I never encounter this because I install Qt at the system level so CPack knows where to find it. You might be able to give CPack some hints on where to find it by prefacing your cmake build command with `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/dell/Qt6.1.2/6.1.2/gcc_64/bin cmake [...]`.

You'll still run into the HDF5 error unless you also add that do the LD_LIBRARY_PATH. But if you don't need the HDF5 functionality, you can disable it by adding `-DBUILD_HDF5=OFF` to your first cmake configure command.
 
Note: You can install Qt6 at the system level on Ubuntu 20.04; if you first do a `sudo add-apt-repository -y ppa:okirby/qt6-backports` then sudo apt-get install qt6-base-dev` will work.

**Comment by somalcy** [comment]
@cboulay sorry for a late reply.

We use the mentioned way to install Qt and it worked.

but we find another problem when we use the command `pip install .`

It gives us the following info:

Processing /home/cuilab/CereLink-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cerebus
  Building wheel for cerebus (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cerebus (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /tmp/pip-build-env-uxwrs74x/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      /home/cuilab/CereLink-master/install False
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing cerebus.egg-info/PKG-INFO
      writing dependency_links to cerebus.egg-info/dependency_links.txt
      writing top-level names to cerebus.egg-info/top_level.txt
      reading manifest file 'cerebus.egg-info/SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'cerebus.egg-info/SOURCES.txt'
      running build_ext
      skipping 'cerebus/cbpy.cpp' Cython extension (up-to-date)
      building 'cerebus.cbpy' extension
      gcc -pthread -B /home/cuilab/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/cuilab/anaconda3/include -fPIC -O2 -isystem /home/cuilab/anaconda3/include -fPIC -I/tmp/pip-build-env-uxwrs74x/overlay/lib/python3.10/site-packages/numpy/core/include -I/home/cuilab/CereLink-master/install/include -I/home/cuilab/anaconda3/include/python3.10 -c cerebus/cbpy.cpp -o build/temp.linux-x86_64-cpython-310/cerebus/cbpy.o
      cerebus/cbpy.cpp:760:10: fatal error: cbproto.h: No such file or directory
        760 | #include "cbproto.h"
            |          ^~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cerebus
Failed to build cerebus
ERROR: Could not build wheels for cerebus, which is required to install pyproject.toml-based projects

We use `cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install -DBUILD_HDF5=OFF -DBUILD_TEST=OFF` to build and `cmake --build build --target package --config Release -j` to release.

It seems that we successfully generate the deb file, and we don't know this problem happen. The info present on screen when we generate the file is:

[  3%] Automatic MOC for target cbsdk_static
[  6%] Automatic MOC for target cbsdk
[  6%] Built target cbsdk_static_autogen
[  6%] Built target cbsdk_autogen
[ 53%] Built target cbsdk_static
[100%] Built target cbsdk
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: CBSDK
CPack: - Install project: CBSDK []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/cuilab/CereLink-master/build/cbsdk_7.6.1_amd64.deb generated.
