### ISSUE TITLE
Cannot find cbproto.h

### ISSUE THREAD

**Issue by somalcy** [CerebusOSS/CereLink#137]
Hi,

We find another problem when we use the command `pip install .`

It gives us the following info:

Processing /home/cuilab/CereLink-master
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cerebus
Building wheel for cerebus (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for cerebus (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [22 lines of output]
/tmp/pip-build-env-uxwrs74x/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for [tool.setuptools] in pyproject.toml is still beta.
config = read_configuration(filepath, True, ignore_option_errors, dist)
/home/cuilab/CereLink-master/install False
running bdist_wheel
running build
running build_py
running egg_info
writing cerebus.egg-info/PKG-INFO
writing dependency_links to cerebus.egg-info/dependency_links.txt
writing top-level names to cerebus.egg-info/top_level.txt
reading manifest file 'cerebus.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'cerebus.egg-info/SOURCES.txt'
running build_ext
skipping 'cerebus/cbpy.cpp' Cython extension (up-to-date)
building 'cerebus.cbpy' extension
gcc -pthread -B /home/cuilab/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/cuilab/anaconda3/include -fPIC -O2 -isystem /home/cuilab/anaconda3/include -fPIC -I/tmp/pip-build-env-uxwrs74x/overlay/lib/python3.10/site-packages/numpy/core/include -I/home/cuilab/CereLink-master/install/include -I/home/cuilab/anaconda3/include/python3.10 -c cerebus/cbpy.cpp -o build/temp.linux-x86_64-cpython-310/cerebus/cbpy.o
cerebus/cbpy.cpp:760:10: fatal error: cbproto.h: No such file or directory
760 | #include "cbproto.h"
| ^~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for cerebus
Failed to build cerebus
ERROR: Could not build wheels for cerebus, which is required to install pyproject.toml-based projects

We use `cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install -DBUILD_HDF5=OFF -DBUILD_TEST=OFF` to build and `cmake --build build --target package --config Release -j to release`.

It seems that we successfully generate the deb file, and we don't know this problem happen. The info present on screen when we generate the file is:

[ 3%] Automatic MOC for target cbsdk_static
[ 6%] Automatic MOC for target cbsdk
[ 6%] Built target cbsdk_static_autogen
[ 6%] Built target cbsdk_autogen
[ 53%] Built target cbsdk_static
[100%] Built target cbsdk
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: CBSDK
CPack: - Install project: CBSDK []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/cuilab/CereLink-master/build/cbsdk_7.6.1_amd64.deb generated.

**Comment by cboulay** [comment]
I think it's because you have to build the `install` target first.

Please try following the CI runner script: https://github.com/CerebusOSS/CereLink/blob/master/.github/workflows/build_cbsdk.yml

**Comment by somalcy** [comment]
I think I misunderstand to document and miss the command `cmake --build build --target install --config Release -j`. The problem is fixed. Thanks a lot!
